### ISSUE TITLE
Do we need workstations w/o habitat installed?

### ISSUE THREAD

**Issue by cheeseplus** [chef-cft/habitat_workstation#6]
We could drop those templates entirely and have the habitat installation be based on a var or attribute.

**Comment by nathenharvey** [comment]
We do need workstations without habitat for the training workshops.  At least for the current iteration of the workshops.

One of the first labs is to install Habitat on the workstation.  I do think this is important for us to keep as part of the workshop so that we can show the various options for installing `hab`.

I don't really care too much about implementation as long as it's easy for an instructor to set-up a lab environment with our without `hab` installed.

**Comment by cheeseplus** [comment]
Cool, my only concern is that we have twice as many templates this way and the base template is really thin as it's just the `habitat_workstaiton::default` recipe and the base image. Will look at streamlining this while maintaining the behaviour.

**Comment by cheeseplus** [comment]
Cool, my only concern is that we have twice as many templates this way and the base template is really thin as it's just the `habitat_workstaiton::default` recipe and the base image. Will look at streamlining this while maintaining the behaviour.

**Comment by cheeseplus** [comment]
We'll build images with habitat and without still but we only need one template as of #10 - closing
